let initState = {
    list : [

       {
           title:"ECB raises interest rates: What you need to know about the global economy this week",
           img:"https://assets.weforum.org/article/image/responsive_big_webp_sjTDUJ6lKIzfFmT95tBUIlanBvYEUBgwfN70PtAeOXg.webp",
           article:"The European Central Bank has raised three of its key interest rates by 50 basis points. It's the first such more in more than a decade.The Asian Development Bank has cut its forecast for GDP growth in developing countries in the region to 4.6% from 5.2%. Bloomberg reports that Angola and Gabons sovereign bonds are trading at distressed levels. It puts the number of emerging market economies at risk of default at record levels.Thailands industrial sentiment rose in June – for the first time in three months. The increase in the Federation of Thai Industries index was attributed to an easing of COVID-19 restrictions and improved economic activity.South African inflation hit a 13-year high in June, reaching 7.4% year on year. This is above analysts' predictions of 7.2%, and up from 6.5% in May.Sterling stabilized against the US dollar and the euro this week, after British inflation was only slightly above forecast.A Reuters poll of economists suggests that the US Federal Reserve will opt for another 75-basis-point rise in interest rates next week. Median predictions from the same poll also showed a 40% probability of a US recession over the coming year.Japan recorded a trade deficit for an 11th month in June, with higher energy prices and a weaker yen increasing the countrys import bill.",
       } ,
       {
        title:"The news from this giant volcano suggests world economy getting worse — and the U.S. may be to blame",
        img:"https://images.mktw.net/im-527729?width=700&size=1.5005861664712778&pixel_ratio=1.5",
        article:"This feature is powered by text-to-speech technology. Want to see it on more articles?Give your feedback below or email audiofeedback@marketwatch.com.When MarketWatch last reported on data from the Mauna Loa Observatory, it painted a pretty grim story of the global economy, in April.That observatory, on the world’s second-largest volcano, measures carbon dioxide in the atmosphere. And the decline in the 12-month average of the year-over-year change in parts per million of atmospheric carbon dioxide preceded the declines in economically sensitive commodities like oil CL.1, +0.92% and copper HG00, +0.58%.Now the news from the volcano is that the rate at which carbon dioxide is accumulating in June dropped to the levels that were typical at the beginning of the 2008 financial crisis.The sanctions on Russia over its invasion of Ukraine has disrupted energy flows. Earlier in the year, China’s severe COVID-19 lockdowns weighed down on activity from the world’s number-two economy. But now China has lifted many of those restrictions, and roadway congestion and port activity is picking up.So that leaves the likely culprit for the latest drop to be the U.S. economy. And that would be consistent with more conventional measures of economic activity. ",
    } ,
    {
        title:"Bank of England and IMF warnings on global economy: Top economics stories to read this week",
        img:"https://assets.weforum.org/article/image/responsive_big_webp_kG5cVecJZsF8YAus8dO-mVBMN5GZUha8obo9N3kxRvU.webp",
        article:"The Indian rupee hit a record low against the US dollar on Tuesday. It came after data showed India's trade deficit reached an all-time high of $25.63 billion.At the same time, the US dollar has continued to strengthen – hitting levels last seen in 2002 – while the euro fell to a two-decade low amid recession concerns. Meanwhile, the British pound dropped to a two-year low against the dollar on Wednesday.Uganda has raised its benchmark interest rate from 7.5% to 8.5%, its highest in more than two years.Inflation expectations have hit record highs in Canada, a Bank of Canada survey of consumers and executives has shown. The current period of high inflation is expected to last longer than previously thought.Retail inflation in Thailand hit a 14-year high in June, with consumer prices increasing by 7.66% from the same period in 2021.South Korean inflation also rose last month, hitting its highest since late 1998. Consumer prices rose by 6% on the year.Australia's central bank has raised interest rates, taking its cash rate to 1.35%.China's debt is likely to hit a record high in 2022, according to a government-backed think tank. Total debt as a percentage of GDP is forecast to reach 275% this year – an increase of 11.3 percentage points",
    } ,
    {
        title:"Explainer: What is a recession?",
        img:"https://assets.weforum.org/article/image/responsive_big_webp_lDeG8sY3GwMEXQVtMI4_a4CmPRIA2_MwCz80E9fMYuU.webp",
        article:"The fallout from the COVID-19 pandemic and the ongoing war in Ukraine has led to a significant economic slump in 2022. Prices for some common commodities are reaching record levels, economic growth is slowing and inflation is rising.As a result, “recession will be hard to avoid” for many countries, World Bank President David Malpass said in June. Not since the 2007-2009 financial crisis - the largest slump after the Great Depression of 1929 - has there been a global economic event of this scale. But what is a recession and how do we decide if one is happening?The definition of a recessionThere is no official, globally recognized definition of a recession.In 1974, the US economist Julius Shiskin described a recession as “two consecutive quarters of declining growth”, and many countries still adhere to that.However, the US has since opted to use a more open definition. The National Bureau of Economic Research (NBER) looks at a variety of factors when deciding whether or not America is in recession. The institution defines the event as “a significant decline in economic activity spread across the economy, lasting more than a few months, normally visible in production, employment, real income, and other indicators. ",
    } ,
    {
        title:"The World Economy Is Imperiled by a Force Hiding in Plain Sight",
        img:"https://static01.nyt.com/images/2022/07/16/multimedia/16global-econ-1/16global-econ-1-superJumbo.jpg?quality=75&auto=webp",
        article:"This past week brought home the magnitude of the overlapping crises assailing the global economy, intensifying fears of recession, job losses, hunger and a plunge on stock markets.At the root of this torment is a force so elemental that it has almost ceased to warrant mention — the pandemic. That force is far from spent, confronting policymakers with grave uncertainty. Their policy tools are better suited for more typical downturns, not a rare combination of diminishing economic growth and soaring prices.Major economies including the United States and France reported their latest data on inflation, revealing that prices on a vast range of goods rose faster in June than anytime in four decades.Those grim numbers increased the likelihood that central banks would move even more aggressively to raise interest rates as a means of slowing price increases — a course expected to cost jobs, batter financial markets and threaten poor countries with debt crises.Those grim numbers increased the likelihood that central banks would move even more aggressively to raise interest rates as a means of slowing price increases — a course expected to cost jobs, batter financial markets and threaten poor countries with debt crises.        ",
    } ,
    {
        title:"This is the key to getting the global economy working again",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7HIv2oo7jcRZgYm2bkYt8BXs86ETAvL3z9Q&usqp=CAU",
        article:"London (CNN Business)Global supply chains are still a snarled mess, disrupting deliveries of goods, adding to headaches for businesses and feeding the worldwide surge in inflation.The good news: There are some indications that the situation is beginning to get better. The bad news: Huge risks — from another spike in coronavirus cases to labor disputes involving US rail workers — make it difficult to assume much confidence, clouding the outlook for the global economy.Whats happening: The recovery from the pandemic unleashed a wave of demand that manufacturers and the network of players that move items around the world werent equipped to handle. But after 18 months of pain, there are some signs conditions are starting to improve.Cargo is flowing more smoothly, and the transit of goods has mostly recovered from the initial shock of the war in Ukraine, Konstantin Krebs, managing partner at Capstan Capital, an investment banking firm that works with investors in containers and container shipping, told me.Containers are coming back onstream, and you can feel that, Krebs said.The Global Supply Chain Pressure Index from the Federal Reserve Bank of New York declined between April and June, though it remains at historically high levels.",
    } ,
    ]}

console.log('#initState',initState)
function economieReduicer(state = initState, action) {
    return state
}
export default economieReduicer