let initState = {

list : [

    {
        title:"Food crisis: Ukraine grain export deal reached with Russia, says Turkey        ",
        img:"https://ichef.bbci.co.uk/news/976/cpsprodpb/0AFA/production/_126001820_mediaitem126001819.jpg",
        article:"It is to be signed on Friday in Istanbul by Ukraine, Russia, Turkey and UN Secretary General Antonio Guterres.The world shortage of Ukrainian grain since Russia's 24 February invasion has left millions at risk of hunger.The invasion sent food prices soaring, so the deal to unblock Ukraine's ports is crucial. Some 20 million tonnes of grain is stuck in silos in Odesa.Ukraine is foreign ministry confirmed that another UN-led round of talks to unblock grain exports would take place in Turkey on Friday - and a document may be signed.But one Ukrainian MP close to the talks voiced caution over the deal.We dont have an agreement yet, Odesa MP Oleksiy Honcharenko told BBC Radio 4s World Tonight programme. We dont trust Russians at all. So let us wait till tomorrow for a final decision and that there will not be some pushbacks from Russians and last minute changes.I keep fingers crossed tomorrow well have a deal and Russia will really respect it.The US State Department welcomed the UN-brokered deal, but said it was focusing on holding Russia accountable for implementing it.We should never have been in this position in the first place. This was a deliberate decision on the part of the Russian Federation to weaponise food,said the departments spokesman Ned Price.",
    } ,
    {
        title:"Europe wildfires: Are they linked to climate change?",
        img:"https://ichef.bbci.co.uk/news/976/cpsprodpb/672A/production/_126001462_gettyimages-1242017178.jpg",
        article:"So far this year, the amount of land burnt by fires across the European Union is more than three times greater than what you would expect by the middle of July.Almost 346,000 hectares 1,370 sq miles of land have been recorded as burnt as of 16 July, according to the European Forest Fire Information System EFFIS.Much of Western Europe has been hit by a record-breaking heatwave, which substantially increases the risk of fires.There are basically three important ingredients for fires - high temperatures, dryness, and high wind,says Dr Friederike Otto, a senior lecturer in climate science at Imperial College London.This fire season is something of an outlier, according to experts.Weve actually seen a decline in the area burned by fires in the Mediterranean and across Europe more widely over the last couple of decades, in a way that doesnt marry up with the rapidly changing risk of fires,says Dr Matthew Jones, a climate scientist at the University of East Anglia.It is a complex picture, experts say, and hard to pick one reason for this trend for the whole of Europe.Over 95% of the fires in Europe are caused by human activity, according to the EFFIS.",
    } ,
    {
        title:"Sherine Abu Akleh: The family of the Al-Jazeera reporter rejects an American report about the bullet that killed her",
        img:"https://ichef.bbci.co.uk/news/800/cpsprodpb/2542/production/_125783590_mediaitem125783586.jpg.webp",
        article:"In an interview with the BBC, Tony Abu Aqleh said the conclusions were unacceptable and insisted that Israeli forces had targeted his sister.Al-Jazeera correspondent was shot in the head last May while covering an Israeli raid in the occupied West Bank.The US said the bullet was too damaged to determine where it had been fired.A senior Palestinian Authority official said the journalists killing was premeditated by an Israeli soldier, accusing the United States of trying to protect Israel.Abu Aqleh portait un casque et un gilet pare-balles portant le mot presse lorsquelle a été tuée alors quelle marchait sur une route de la ville cisjordanienne de Jénine le 11 mai, à proximité dune fusillade entre les forces israéliennes et des hommes armés palestiniens, et un journaliste palestinien Ali a été blessé dans les incidents.Al-Samudi et dautres journalistes ont déclaré que les tirs provenaient des forces israéliennes stationnées sur la route.De nombreuses enquêtes médiatiques et menées par le Bureau des droits de lhomme des Nations Unies ont conclu que les forces israéliennes avaient tiré la balle qui avait tué la journaliste, ou semblaient lavoir abattue.",
    } ,
    {
        title:"Former U.N. 'relief chief' shares his secret for coping with crises: a 'sunny gene'",
        img:"https://media.npr.org/assets/img/2022/07/21/gettyimages-950563242_custom-5b4406b995bb6760490004836c5394da64662cf1-s900-c85.webp",
        article:"It's a grueling and grinding job.Sir Mark Lowcock has spent nearly 40 years getting critical help to those suffering through a variety of crises: civil wars, famine, earthquakes and volcanic eruptions. Along the way, he says he confronted an enormous, horrifying catalog of human misery and human brutality toward other human beings.How does he find the strength to keep on going?I've been blessed with a sunny gene, he says. Unless you are able to see a brighter future, you dont hang around for decades in this work.That positive outlook has supported him through his role as the world's most senior humanitarian official: the relief chief of the U.N. Office for the Coordination of Humanitarian Affairs, a position he held from 2017 to 2021. His job was to encourage aid groups like the Red Cross and U.N. agencies like the World Food Programme and UNICEF to work together — and raise funds for them to assist those in need.He's now published a memoir reflecting on his time at the U.N., titled Relief Chief: A Manifesto for Saving Lives in Dire Times — and proposing solutions to how to support people faster and more effectively.",
    } ,
    {
        title:"WHO reconsiders whether to declare monkeypox a global crisis        ",
        img:"https://d3i6fh83elv35t.cloudfront.net/static/2022/05/monkeypox-1200x800.jpg",
        article:"LONDON (AP) — As the World Health Organization’s emergency committee convened Thursday to consider for the second time within weeks whether to declare monkeypox a global crisis, some scientists said the striking differences between the outbreaks in Africa and in developed countries will complicate any coordinated response.African officials say they are already treating the continent’s epidemic as an emergency. But experts elsewhere say the mild version of monkeypox in Europe, North America and beyond makes an emergency declaration unnecessary even if the virus can’t be stopped. British officials recently downgraded their assessment of the disease, given its lack of severity.WATCH: States grapple with rising demand for monkeypox vaccines“I remain concerned about the number of cases, in an increasing number of countries, that have been reported,” WHO Director-General Tedros Adhanom Ghebreyesus told the emergency committee as its meeting got underway.He said it was “pleasing” to note falling numbers of monkeypox cases in some countries but that the virus is still increasing elsewhere and that six countries reported their first infections last week.",
    } ,
    {
        title:"Convergence of conflicts, COVID and climate crises, jeopardize global goals           ",
        img:"https://global.unitednations.entermediadb.net/assets/mediadb/services/module/asset/downloads/preset/Libraries/Production+Library/07-07-2022-Msafer-Yatta-Palestine-OCHA.jpg/image1170x530cropped.jpg",
        article:"The pandemic has undermined countries’ effort to reach the ambitious global goals – and its impact far from over.Deaths directly and indirectly attributable to the coronavirus, reached 15 million by the end of last year, said the report, wiping out over four years of progress in alleviating poverty as well as severely disrupting essential health services and derailing hard-won progress on SDG 3.Moreover, since 2020, some 147 million students have missed over half of their in-person instruction.Meanwhile, the world is on the verge of a climate catastrophe where billions are already suffering the consequences of global warming and increasingly extreme weather.Energy-related CO2 emissions rose by six per cent last year, reaching their highest level ever, completely wiping out pandemic-related declines.To avoid the worst effects of climate change, global greenhouse gas emissions must peak before 2025 and then decline by 43 per cent by 2030, falling to net zero by 2050.Instead, under current voluntary national commitments (NDCs) to climate action, greenhouse gas emissions are set to rise nearly 14 per cent over the next decade.And this year, an estimated 17 million metric tons of plastic entered the ocean – a number that is expected to double or triple by 2040.",
    } ,

]}
function worldCrisesReducer(state = initState, action) {
    return state
}
export default worldCrisesReducer